### ISSUE TITLE
issue: cant start X server in CLI

### ISSUE THREAD

**Issue by frayar22** [chiru-no/cloveros#9]
Probably im a pleb, but after cloveos asked me to startx and i replied no, trying to start it again using the startx command gives me the error of the screenshot.
![image](https://user-images.githubusercontent.com/4948877/27257397-6f3a625e-539a-11e7-8b61-6135e30c3d1e.png)

**Comment by chiru-no** [comment]
Use xinit /usr/bin/twm

Replace that last part with any other WM or process of your choice.
